domain_path: /home2/etudiants/master2/abdennour.guessoum/SOC/Vitis/platform/export/platform/sw/standalone_ps7_cortexa9_0
app_src_dir: /tools/Xilinx/Vitis/2023.2/data/embeddedsw/lib/sw_apps/hello_world
template: hello_world
